{
    "name": "hospital management system",
    "author": "priyanka",
    "version": "18.0",
    "license": "LGPL-3",
    "depends": ["base","sale_management","sale", "mail", "report_xlsx","account" ],
    "data":
        [
            "security/ir.model.access.csv",
            "security/security.xml",
            "views/view_patient.xml",
            "views/view_doctor.xml",
            "views/view_sale_order.xml",
            "views/view_purchase_order.xml",
            "views/view_appointment.xml",
            "data/patient_confirm_mail.xml",
            "data/ir.sequence.xml",
            "data/patient_appointment_mail.xml",
            "views/view_patient_lines.xml",
            "report/report_patient_template.xml",
            "report/report.xml",
            "wizard/patient_wizard_invoices.xml",
            "wizard/sale_order_wizard.xml",
            "views/report_wizard_view.xml",
            "views/view_invoice.xml",
            "report/report_sales_wizard_template.xml",
            "views/menu.xml", ],
}
